spring:
  application:
    name: demo-spring-boot-hibernate-jpa

  datasource:
    url: jdbc:mysql://localhost:21212/WorkPlace
    username: work
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082
